US792072: Improve the poison message error description
CAFapi/caf-dependency-management-bom pull request #58
Opened 2023-10-23 16:36 UTC by caoimhelynch

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=792072

2023-10-23 16:44 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~caf-dependency-management-bom~US792072~CI

2023-10-24 14:49 UTC, caoimhelynch commented
@dermot-hardy Would you mind checking this. @andyreidz is not sure about this

2023-10-24 16:57 UTC, dermot-hardy requested changes
Let's consider this to be outside the scope of [`US792072`](https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=792072), and just make the Worker Framework changes for that ticket.

2023-10-24 16:57 UTC, closed without merging

2023-10-27 09:36 UTC, tonymcveigh commented
TEST